<?php

namespace App\Modules\Settings\Controllers;

use App\Modules\Settings\Models\Country;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Http;

class CountryListController
{
    public function index(): JsonResponse
    {
        $apiKey = config('services.restcountries.key');

        // Try to fetch from REST Countries API v5
        if ($apiKey) {
            try {
                $response = Http::timeout(10)
                    ->withHeaders(['Authorization' => "Bearer {$apiKey}"])
                    ->get('https://api.restcountries.com/countries/v5');

                if ($response->successful()) {
                    $data = $response->json();

                    // Extract and format the countries
                    if (isset($data['data']['objects']) && is_array($data['data']['objects'])) {
                        $countries = collect($data['data']['objects'])
                            ->map(fn ($country) => [
                                'code' => $country['codes']['alpha_2'] ?? '',
                                'name' => $country['names']['common'] ?? $country['names']['official'] ?? '',
                                'flag_emoji' => $country['flag']['emoji'] ?? '',
                                'region' => $country['region'] ?? '',
                                'capital' => is_array($country['capital']) ? $country['capital'][0] ?? '' : '',
                                'currencies' => $country['currencies'] ?? [],
                                'languages' => $country['languages'] ?? [],
                            ])
                            ->filter(fn ($c) => !empty($c['code']) && !empty($c['name']))
                            ->sortBy('name')
                            ->values()
                            ->all();

                        // Optionally sync to database
                        foreach ($countries as $countryData) {
                            Country::updateOrCreate(
                                ['code' => $countryData['code']],
                                [
                                    'name' => $countryData['name'],
                                    'capital' => $countryData['capital'],
                                    'region' => $countryData['region'],
                                    'flag_emoji' => $countryData['flag_emoji'],
                                    'is_active' => false, // Inactive by default until admin approves
                                ]
                            );
                        }

                        return response()->json(['countries' => $countries]);
                    }
                }
            } catch (\Exception $e) {
                \Log::warning('REST Countries API error: ' . $e->getMessage());
                // Fall through to fallback list
            }
        }

        // Fallback: return countries from database or hardcoded list
        $countries = Country::all()
            ->map(fn (Country $c) => [
                'code' => $c->code,
                'name' => $c->name,
                'flag_emoji' => $c->flag_emoji ?? '',
                'region' => $c->region ?? '',
                'capital' => $c->capital ?? '',
            ])
            ->sortBy('name')
            ->values()
            ->all();

        // If database is empty, return hardcoded list
        if (empty($countries)) {
            $countries = [
                ['code' => 'AF', 'name' => 'Afghanistan', 'flag_emoji' => '🇦🇫', 'capital' => 'Kabul', 'region' => 'Asia'],
                ['code' => 'AL', 'name' => 'Albania', 'flag_emoji' => '🇦🇱', 'capital' => 'Tirana', 'region' => 'Europe'],
                ['code' => 'DZ', 'name' => 'Algeria', 'flag_emoji' => '🇩🇿', 'capital' => 'Algiers', 'region' => 'Africa'],
                ['code' => 'AD', 'name' => 'Andorra', 'flag_emoji' => '🇦🇩', 'capital' => 'Andorra la Vella', 'region' => 'Europe'],
                ['code' => 'AO', 'name' => 'Angola', 'flag_emoji' => '🇦🇴', 'capital' => 'Luanda', 'region' => 'Africa'],
                ['code' => 'AG', 'name' => 'Antigua and Barbuda', 'flag_emoji' => '🇦🇬', 'capital' => 'Saint John\'s', 'region' => 'Americas'],
                ['code' => 'AR', 'name' => 'Argentina', 'flag_emoji' => '🇦🇷', 'capital' => 'Buenos Aires', 'region' => 'Americas'],
                ['code' => 'AM', 'name' => 'Armenia', 'flag_emoji' => '🇦🇲', 'capital' => 'Yerevan', 'region' => 'Asia'],
                ['code' => 'AU', 'name' => 'Australia', 'flag_emoji' => '🇦🇺', 'capital' => 'Canberra', 'region' => 'Oceania'],
                ['code' => 'AT', 'name' => 'Austria', 'flag_emoji' => '🇦🇹', 'capital' => 'Vienna', 'region' => 'Europe'],
                ['code' => 'AZ', 'name' => 'Azerbaijan', 'flag_emoji' => '🇦🇿', 'capital' => 'Baku', 'region' => 'Asia'],
                ['code' => 'BS', 'name' => 'Bahamas', 'flag_emoji' => '🇧🇸', 'capital' => 'Nassau', 'region' => 'Americas'],
                ['code' => 'BH', 'name' => 'Bahrain', 'flag_emoji' => '🇧🇭', 'capital' => 'Manama', 'region' => 'Asia'],
                ['code' => 'BD', 'name' => 'Bangladesh', 'flag_emoji' => '🇧🇩', 'capital' => 'Dhaka', 'region' => 'Asia'],
                ['code' => 'BB', 'name' => 'Barbados', 'flag_emoji' => '🇧🇧', 'capital' => 'Bridgetown', 'region' => 'Americas'],
                ['code' => 'BY', 'name' => 'Belarus', 'flag_emoji' => '🇧🇾', 'capital' => 'Minsk', 'region' => 'Europe'],
                ['code' => 'BE', 'name' => 'Belgium', 'flag_emoji' => '🇧🇪', 'capital' => 'Brussels', 'region' => 'Europe'],
                ['code' => 'BZ', 'name' => 'Belize', 'flag_emoji' => '🇧🇿', 'capital' => 'Belmopan', 'region' => 'Americas'],
                ['code' => 'BJ', 'name' => 'Benin', 'flag_emoji' => '🇧🇯', 'capital' => 'Porto-Novo', 'region' => 'Africa'],
                ['code' => 'BT', 'name' => 'Bhutan', 'flag_emoji' => '🇧🇹', 'capital' => 'Thimphu', 'region' => 'Asia'],
                ['code' => 'BO', 'name' => 'Bolivia', 'flag_emoji' => '🇧🇴', 'capital' => 'La Paz', 'region' => 'Americas'],
                ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'flag_emoji' => '🇧🇦', 'capital' => 'Sarajevo', 'region' => 'Europe'],
                ['code' => 'BW', 'name' => 'Botswana', 'flag_emoji' => '🇧🇼', 'capital' => 'Gaborone', 'region' => 'Africa'],
                ['code' => 'BR', 'name' => 'Brazil', 'flag_emoji' => '🇧🇷', 'capital' => 'Brasília', 'region' => 'Americas'],
                ['code' => 'BN', 'name' => 'Brunei', 'flag_emoji' => '🇧🇳', 'capital' => 'Bandar Seri Begawan', 'region' => 'Asia'],
                ['code' => 'BG', 'name' => 'Bulgaria', 'flag_emoji' => '🇧🇬', 'capital' => 'Sofia', 'region' => 'Europe'],
                ['code' => 'BF', 'name' => 'Burkina Faso', 'flag_emoji' => '🇧🇫', 'capital' => 'Ouagadougou', 'region' => 'Africa'],
                ['code' => 'BI', 'name' => 'Burundi', 'flag_emoji' => '🇧🇮', 'capital' => 'Gitega', 'region' => 'Africa'],
                ['code' => 'KH', 'name' => 'Cambodia', 'flag_emoji' => '🇰🇭', 'capital' => 'Phnom Penh', 'region' => 'Asia'],
                ['code' => 'CM', 'name' => 'Cameroon', 'flag_emoji' => '🇨🇲', 'capital' => 'Yaoundé', 'region' => 'Africa'],
                ['code' => 'CA', 'name' => 'Canada', 'flag_emoji' => '🇨🇦', 'capital' => 'Ottawa', 'region' => 'Americas'],
                ['code' => 'CV', 'name' => 'Cape Verde', 'flag_emoji' => '🇨🇻', 'capital' => 'Praia', 'region' => 'Africa'],
                ['code' => 'CF', 'name' => 'Central African Republic', 'flag_emoji' => '🇨🇫', 'capital' => 'Bangui', 'region' => 'Africa'],
                ['code' => 'TD', 'name' => 'Chad', 'flag_emoji' => '🇹🇩', 'capital' => 'N\'Djamena', 'region' => 'Africa'],
                ['code' => 'CL', 'name' => 'Chile', 'flag_emoji' => '🇨🇱', 'capital' => 'Santiago', 'region' => 'Americas'],
                ['code' => 'CN', 'name' => 'China', 'flag_emoji' => '🇨🇳', 'capital' => 'Beijing', 'region' => 'Asia'],
                ['code' => 'CO', 'name' => 'Colombia', 'flag_emoji' => '🇨🇴', 'capital' => 'Bogotá', 'region' => 'Americas'],
                ['code' => 'KM', 'name' => 'Comoros', 'flag_emoji' => '🇰🇲', 'capital' => 'Moroni', 'region' => 'Africa'],
                ['code' => 'CG', 'name' => 'Congo', 'flag_emoji' => '🇨🇬', 'capital' => 'Brazzaville', 'region' => 'Africa'],
                ['code' => 'CD', 'name' => 'Democratic Republic of the Congo', 'flag_emoji' => '🇨🇩', 'capital' => 'Kinshasa', 'region' => 'Africa'],
                ['code' => 'CR', 'name' => 'Costa Rica', 'flag_emoji' => '🇨🇷', 'capital' => 'San José', 'region' => 'Americas'],
                ['code' => 'HR', 'name' => 'Croatia', 'flag_emoji' => '🇭🇷', 'capital' => 'Zagreb', 'region' => 'Europe'],
                ['code' => 'CU', 'name' => 'Cuba', 'flag_emoji' => '🇨🇺', 'capital' => 'Havana', 'region' => 'Americas'],
                ['code' => 'CY', 'name' => 'Cyprus', 'flag_emoji' => '🇨🇾', 'capital' => 'Nicosia', 'region' => 'Europe'],
                ['code' => 'CZ', 'name' => 'Czech Republic', 'flag_emoji' => '🇨🇿', 'capital' => 'Prague', 'region' => 'Europe'],
                ['code' => 'DK', 'name' => 'Denmark', 'flag_emoji' => '🇩🇰', 'capital' => 'Copenhagen', 'region' => 'Europe'],
                ['code' => 'DJ', 'name' => 'Djibouti', 'flag_emoji' => '🇩🇯', 'capital' => 'Djibouti City', 'region' => 'Africa'],
                ['code' => 'DM', 'name' => 'Dominica', 'flag_emoji' => '🇩🇲', 'capital' => 'Roseau', 'region' => 'Americas'],
                ['code' => 'DO', 'name' => 'Dominican Republic', 'flag_emoji' => '🇩🇴', 'capital' => 'Santo Domingo', 'region' => 'Americas'],
                ['code' => 'EC', 'name' => 'Ecuador', 'flag_emoji' => '🇪🇨', 'capital' => 'Quito', 'region' => 'Americas'],
                ['code' => 'EG', 'name' => 'Egypt', 'flag_emoji' => '🇪🇬', 'capital' => 'Cairo', 'region' => 'Africa'],
                ['code' => 'SV', 'name' => 'El Salvador', 'flag_emoji' => '🇸🇻', 'capital' => 'San Salvador', 'region' => 'Americas'],
                ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'flag_emoji' => '🇬🇶', 'capital' => 'Malabo', 'region' => 'Africa'],
                ['code' => 'ER', 'name' => 'Eritrea', 'flag_emoji' => '🇪🇷', 'capital' => 'Asmara', 'region' => 'Africa'],
                ['code' => 'EE', 'name' => 'Estonia', 'flag_emoji' => '🇪🇪', 'capital' => 'Tallinn', 'region' => 'Europe'],
                ['code' => 'ET', 'name' => 'Ethiopia', 'flag_emoji' => '🇪🇹', 'capital' => 'Addis Ababa', 'region' => 'Africa'],
                ['code' => 'FJ', 'name' => 'Fiji', 'flag_emoji' => '🇫🇯', 'capital' => 'Suva', 'region' => 'Oceania'],
                ['code' => 'FI', 'name' => 'Finland', 'flag_emoji' => '🇫🇮', 'capital' => 'Helsinki', 'region' => 'Europe'],
                ['code' => 'FR', 'name' => 'France', 'flag_emoji' => '🇫🇷', 'capital' => 'Paris', 'region' => 'Europe'],
                ['code' => 'GA', 'name' => 'Gabon', 'flag_emoji' => '🇬🇦', 'capital' => 'Libreville', 'region' => 'Africa'],
                ['code' => 'GM', 'name' => 'Gambia', 'flag_emoji' => '🇬🇲', 'capital' => 'Banjul', 'region' => 'Africa'],
                ['code' => 'GE', 'name' => 'Georgia', 'flag_emoji' => '🇬🇪', 'capital' => 'Tbilisi', 'region' => 'Asia'],
                ['code' => 'DE', 'name' => 'Germany', 'flag_emoji' => '🇩🇪', 'capital' => 'Berlin', 'region' => 'Europe'],
                ['code' => 'GH', 'name' => 'Ghana', 'flag_emoji' => '🇬🇭', 'capital' => 'Accra', 'region' => 'Africa'],
                ['code' => 'GR', 'name' => 'Greece', 'flag_emoji' => '🇬🇷', 'capital' => 'Athens', 'region' => 'Europe'],
                ['code' => 'GD', 'name' => 'Grenada', 'flag_emoji' => '🇬🇩', 'capital' => 'Saint George\'s', 'region' => 'Americas'],
                ['code' => 'GT', 'name' => 'Guatemala', 'flag_emoji' => '🇬🇹', 'capital' => 'Guatemala City', 'region' => 'Americas'],
                ['code' => 'GN', 'name' => 'Guinea', 'flag_emoji' => '🇬🇳', 'capital' => 'Conakry', 'region' => 'Africa'],
                ['code' => 'GW', 'name' => 'Guinea-Bissau', 'flag_emoji' => '🇬🇼', 'capital' => 'Bissau', 'region' => 'Africa'],
                ['code' => 'GY', 'name' => 'Guyana', 'flag_emoji' => '🇬🇾', 'capital' => 'Georgetown', 'region' => 'Americas'],
                ['code' => 'HT', 'name' => 'Haiti', 'flag_emoji' => '🇭🇹', 'capital' => 'Port-au-Prince', 'region' => 'Americas'],
                ['code' => 'HN', 'name' => 'Honduras', 'flag_emoji' => '🇭🇳', 'capital' => 'Tegucigalpa', 'region' => 'Americas'],
                ['code' => 'HU', 'name' => 'Hungary', 'flag_emoji' => '🇭🇺', 'capital' => 'Budapest', 'region' => 'Europe'],
                ['code' => 'IS', 'name' => 'Iceland', 'flag_emoji' => '🇮🇸', 'capital' => 'Reykjavik', 'region' => 'Europe'],
                ['code' => 'IN', 'name' => 'India', 'flag_emoji' => '🇮🇳', 'capital' => 'New Delhi', 'region' => 'Asia'],
                ['code' => 'ID', 'name' => 'Indonesia', 'flag_emoji' => '🇮🇩', 'capital' => 'Jakarta', 'region' => 'Asia'],
                ['code' => 'IR', 'name' => 'Iran', 'flag_emoji' => '🇮🇷', 'capital' => 'Tehran', 'region' => 'Asia'],
                ['code' => 'IQ', 'name' => 'Iraq', 'flag_emoji' => '🇮🇶', 'capital' => 'Baghdad', 'region' => 'Asia'],
                ['code' => 'IE', 'name' => 'Ireland', 'flag_emoji' => '🇮🇪', 'capital' => 'Dublin', 'region' => 'Europe'],
                ['code' => 'IL', 'name' => 'Israel', 'flag_emoji' => '🇮🇱', 'capital' => 'Jerusalem', 'region' => 'Asia'],
                ['code' => 'IT', 'name' => 'Italy', 'flag_emoji' => '🇮🇹', 'capital' => 'Rome', 'region' => 'Europe'],
                ['code' => 'CI', 'name' => 'Ivory Coast', 'flag_emoji' => '🇨🇮', 'capital' => 'Yamoussoukro', 'region' => 'Africa'],
                ['code' => 'JM', 'name' => 'Jamaica', 'flag_emoji' => '🇯🇲', 'capital' => 'Kingston', 'region' => 'Americas'],
                ['code' => 'JP', 'name' => 'Japan', 'flag_emoji' => '🇯🇵', 'capital' => 'Tokyo', 'region' => 'Asia'],
                ['code' => 'JO', 'name' => 'Jordan', 'flag_emoji' => '🇯🇴', 'capital' => 'Amman', 'region' => 'Asia'],
                ['code' => 'KZ', 'name' => 'Kazakhstan', 'flag_emoji' => '🇰🇿', 'capital' => 'Nur-Sultan', 'region' => 'Asia'],
                ['code' => 'KE', 'name' => 'Kenya', 'flag_emoji' => '🇰🇪', 'capital' => 'Nairobi', 'region' => 'Africa'],
                ['code' => 'KI', 'name' => 'Kiribati', 'flag_emoji' => '🇰🇮', 'capital' => 'Tarawa', 'region' => 'Oceania'],
                ['code' => 'KP', 'name' => 'North Korea', 'flag_emoji' => '🇰🇵', 'capital' => 'Pyongyang', 'region' => 'Asia'],
                ['code' => 'KR', 'name' => 'South Korea', 'flag_emoji' => '🇰🇷', 'capital' => 'Seoul', 'region' => 'Asia'],
                ['code' => 'KW', 'name' => 'Kuwait', 'flag_emoji' => '🇰🇼', 'capital' => 'Kuwait City', 'region' => 'Asia'],
                ['code' => 'KG', 'name' => 'Kyrgyzstan', 'flag_emoji' => '🇰🇬', 'capital' => 'Bishkek', 'region' => 'Asia'],
                ['code' => 'LA', 'name' => 'Laos', 'flag_emoji' => '🇱🇦', 'capital' => 'Vientiane', 'region' => 'Asia'],
                ['code' => 'LV', 'name' => 'Latvia', 'flag_emoji' => '🇱🇻', 'capital' => 'Riga', 'region' => 'Europe'],
                ['code' => 'LB', 'name' => 'Lebanon', 'flag_emoji' => '🇱🇧', 'capital' => 'Beirut', 'region' => 'Asia'],
                ['code' => 'LS', 'name' => 'Lesotho', 'flag_emoji' => '🇱🇸', 'capital' => 'Maseru', 'region' => 'Africa'],
                ['code' => 'LR', 'name' => 'Liberia', 'flag_emoji' => '🇱🇷', 'capital' => 'Monrovia', 'region' => 'Africa'],
                ['code' => 'LY', 'name' => 'Libya', 'flag_emoji' => '🇱🇾', 'capital' => 'Tripoli', 'region' => 'Africa'],
                ['code' => 'LI', 'name' => 'Liechtenstein', 'flag_emoji' => '🇱🇮', 'capital' => 'Vaduz', 'region' => 'Europe'],
                ['code' => 'LT', 'name' => 'Lithuania', 'flag_emoji' => '🇱🇹', 'capital' => 'Vilnius', 'region' => 'Europe'],
                ['code' => 'LU', 'name' => 'Luxembourg', 'flag_emoji' => '🇱🇺', 'capital' => 'Luxembourg City', 'region' => 'Europe'],
                ['code' => 'MG', 'name' => 'Madagascar', 'flag_emoji' => '🇲🇬', 'capital' => 'Antananarivo', 'region' => 'Africa'],
                ['code' => 'MW', 'name' => 'Malawi', 'flag_emoji' => '🇲🇼', 'capital' => 'Lilongwe', 'region' => 'Africa'],
                ['code' => 'MY', 'name' => 'Malaysia', 'flag_emoji' => '🇲🇾', 'capital' => 'Kuala Lumpur', 'region' => 'Asia'],
                ['code' => 'MV', 'name' => 'Maldives', 'flag_emoji' => '🇲🇻', 'capital' => 'Malé', 'region' => 'Asia'],
                ['code' => 'ML', 'name' => 'Mali', 'flag_emoji' => '🇲🇱', 'capital' => 'Bamako', 'region' => 'Africa'],
                ['code' => 'MT', 'name' => 'Malta', 'flag_emoji' => '🇲🇹', 'capital' => 'Valletta', 'region' => 'Europe'],
                ['code' => 'MH', 'name' => 'Marshall Islands', 'flag_emoji' => '🇲🇭', 'capital' => 'Majuro', 'region' => 'Oceania'],
                ['code' => 'MR', 'name' => 'Mauritania', 'flag_emoji' => '🇲🇷', 'capital' => 'Nouakchott', 'region' => 'Africa'],
                ['code' => 'MU', 'name' => 'Mauritius', 'flag_emoji' => '🇲🇺', 'capital' => 'Port Louis', 'region' => 'Africa'],
                ['code' => 'MX', 'name' => 'Mexico', 'flag_emoji' => '🇲🇽', 'capital' => 'Mexico City', 'region' => 'Americas'],
                ['code' => 'FM', 'name' => 'Micronesia', 'flag_emoji' => '🇫🇲', 'capital' => 'Palikir', 'region' => 'Oceania'],
                ['code' => 'MD', 'name' => 'Moldova', 'flag_emoji' => '🇲🇩', 'capital' => 'Chișinău', 'region' => 'Europe'],
                ['code' => 'MC', 'name' => 'Monaco', 'flag_emoji' => '🇲🇨', 'capital' => 'Monaco', 'region' => 'Europe'],
                ['code' => 'MN', 'name' => 'Mongolia', 'flag_emoji' => '🇲🇳', 'capital' => 'Ulaanbaatar', 'region' => 'Asia'],
                ['code' => 'ME', 'name' => 'Montenegro', 'flag_emoji' => '🇲🇪', 'capital' => 'Podgorica', 'region' => 'Europe'],
                ['code' => 'MA', 'name' => 'Morocco', 'flag_emoji' => '🇲🇦', 'capital' => 'Rabat', 'region' => 'Africa'],
                ['code' => 'MZ', 'name' => 'Mozambique', 'flag_emoji' => '🇲🇿', 'capital' => 'Maputo', 'region' => 'Africa'],
                ['code' => 'MM', 'name' => 'Myanmar', 'flag_emoji' => '🇲🇲', 'capital' => 'Naypyidaw', 'region' => 'Asia'],
                ['code' => 'NA', 'name' => 'Namibia', 'flag_emoji' => '🇳🇦', 'capital' => 'Windhoek', 'region' => 'Africa'],
                ['code' => 'NR', 'name' => 'Nauru', 'flag_emoji' => '🇳🇷', 'capital' => 'Yaren', 'region' => 'Oceania'],
                ['code' => 'NP', 'name' => 'Nepal', 'flag_emoji' => '🇳🇵', 'capital' => 'Kathmandu', 'region' => 'Asia'],
                ['code' => 'NL', 'name' => 'Netherlands', 'flag_emoji' => '🇳🇱', 'capital' => 'Amsterdam', 'region' => 'Europe'],
                ['code' => 'NZ', 'name' => 'New Zealand', 'flag_emoji' => '🇳🇿', 'capital' => 'Wellington', 'region' => 'Oceania'],
                ['code' => 'NI', 'name' => 'Nicaragua', 'flag_emoji' => '🇳🇮', 'capital' => 'Managua', 'region' => 'Americas'],
                ['code' => 'NE', 'name' => 'Niger', 'flag_emoji' => '🇳🇪', 'capital' => 'Niamey', 'region' => 'Africa'],
                ['code' => 'NG', 'name' => 'Nigeria', 'flag_emoji' => '🇳🇬', 'capital' => 'Abuja', 'region' => 'Africa'],
                ['code' => 'NO', 'name' => 'Norway', 'flag_emoji' => '🇳🇴', 'capital' => 'Oslo', 'region' => 'Europe'],
                ['code' => 'OM', 'name' => 'Oman', 'flag_emoji' => '🇴🇲', 'capital' => 'Muscat', 'region' => 'Asia'],
                ['code' => 'PK', 'name' => 'Pakistan', 'flag_emoji' => '🇵🇰', 'capital' => 'Islamabad', 'region' => 'Asia'],
                ['code' => 'PW', 'name' => 'Palau', 'flag_emoji' => '🇵🇼', 'capital' => 'Ngerulmud', 'region' => 'Oceania'],
                ['code' => 'PS', 'name' => 'Palestine', 'flag_emoji' => '🇵🇸', 'capital' => 'Ramallah', 'region' => 'Asia'],
                ['code' => 'PA', 'name' => 'Panama', 'flag_emoji' => '🇵🇦', 'capital' => 'Panama City', 'region' => 'Americas'],
                ['code' => 'PG', 'name' => 'Papua New Guinea', 'flag_emoji' => '🇵🇬', 'capital' => 'Port Moresby', 'region' => 'Oceania'],
                ['code' => 'PY', 'name' => 'Paraguay', 'flag_emoji' => '🇵🇾', 'capital' => 'Asunción', 'region' => 'Americas'],
                ['code' => 'PE', 'name' => 'Peru', 'flag_emoji' => '🇵🇪', 'capital' => 'Lima', 'region' => 'Americas'],
                ['code' => 'PH', 'name' => 'Philippines', 'flag_emoji' => '🇵🇭', 'capital' => 'Manila', 'region' => 'Asia'],
                ['code' => 'PL', 'name' => 'Poland', 'flag_emoji' => '🇵🇱', 'capital' => 'Warsaw', 'region' => 'Europe'],
                ['code' => 'PT', 'name' => 'Portugal', 'flag_emoji' => '🇵🇹', 'capital' => 'Lisbon', 'region' => 'Europe'],
                ['code' => 'QA', 'name' => 'Qatar', 'flag_emoji' => '🇶🇦', 'capital' => 'Doha', 'region' => 'Asia'],
                ['code' => 'RO', 'name' => 'Romania', 'flag_emoji' => '🇷🇴', 'capital' => 'Bucharest', 'region' => 'Europe'],
                ['code' => 'RU', 'name' => 'Russia', 'flag_emoji' => '🇷🇺', 'capital' => 'Moscow', 'region' => 'Europe'],
                ['code' => 'RW', 'name' => 'Rwanda', 'flag_emoji' => '🇷🇼', 'capital' => 'Kigali', 'region' => 'Africa'],
                ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'flag_emoji' => '🇰🇳', 'capital' => 'Basseterre', 'region' => 'Americas'],
                ['code' => 'LC', 'name' => 'Saint Lucia', 'flag_emoji' => '🇱🇨', 'capital' => 'Castries', 'region' => 'Americas'],
                ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'flag_emoji' => '🇻🇨', 'capital' => 'Kingstown', 'region' => 'Americas'],
                ['code' => 'WS', 'name' => 'Samoa', 'flag_emoji' => '🇼🇸', 'capital' => 'Apia', 'region' => 'Oceania'],
                ['code' => 'SM', 'name' => 'San Marino', 'flag_emoji' => '🇸🇲', 'capital' => 'San Marino', 'region' => 'Europe'],
                ['code' => 'ST', 'name' => 'Sao Tome and Principe', 'flag_emoji' => '🇸🇹', 'capital' => 'São Tomé', 'region' => 'Africa'],
                ['code' => 'SA', 'name' => 'Saudi Arabia', 'flag_emoji' => '🇸🇦', 'capital' => 'Riyadh', 'region' => 'Asia'],
                ['code' => 'SN', 'name' => 'Senegal', 'flag_emoji' => '🇸🇳', 'capital' => 'Dakar', 'region' => 'Africa'],
                ['code' => 'RS', 'name' => 'Serbia', 'flag_emoji' => '🇷🇸', 'capital' => 'Belgrade', 'region' => 'Europe'],
                ['code' => 'SC', 'name' => 'Seychelles', 'flag_emoji' => '🇸🇨', 'capital' => 'Victoria', 'region' => 'Africa'],
                ['code' => 'SL', 'name' => 'Sierra Leone', 'flag_emoji' => '🇸🇱', 'capital' => 'Freetown', 'region' => 'Africa'],
                ['code' => 'SG', 'name' => 'Singapore', 'flag_emoji' => '🇸🇬', 'capital' => 'Singapore', 'region' => 'Asia'],
                ['code' => 'SK', 'name' => 'Slovakia', 'flag_emoji' => '🇸🇰', 'capital' => 'Bratislava', 'region' => 'Europe'],
                ['code' => 'SI', 'name' => 'Slovenia', 'flag_emoji' => '🇸🇮', 'capital' => 'Ljubljana', 'region' => 'Europe'],
                ['code' => 'SB', 'name' => 'Solomon Islands', 'flag_emoji' => '🇸🇧', 'capital' => 'Honiara', 'region' => 'Oceania'],
                ['code' => 'SO', 'name' => 'Somalia', 'flag_emoji' => '🇸🇴', 'capital' => 'Mogadishu', 'region' => 'Africa'],
                ['code' => 'ZA', 'name' => 'South Africa', 'flag_emoji' => '🇿🇦', 'capital' => 'Pretoria', 'region' => 'Africa'],
                ['code' => 'SS', 'name' => 'South Sudan', 'flag_emoji' => '🇸🇸', 'capital' => 'Juba', 'region' => 'Africa'],
                ['code' => 'ES', 'name' => 'Spain', 'flag_emoji' => '🇪🇸', 'capital' => 'Madrid', 'region' => 'Europe'],
                ['code' => 'LK', 'name' => 'Sri Lanka', 'flag_emoji' => '🇱🇰', 'capital' => 'Colombo', 'region' => 'Asia'],
                ['code' => 'SD', 'name' => 'Sudan', 'flag_emoji' => '🇸🇩', 'capital' => 'Khartoum', 'region' => 'Africa'],
                ['code' => 'SR', 'name' => 'Suriname', 'flag_emoji' => '🇸🇷', 'capital' => 'Paramaribo', 'region' => 'Americas'],
                ['code' => 'SE', 'name' => 'Sweden', 'flag_emoji' => '🇸🇪', 'capital' => 'Stockholm', 'region' => 'Europe'],
                ['code' => 'CH', 'name' => 'Switzerland', 'flag_emoji' => '🇨🇭', 'capital' => 'Bern', 'region' => 'Europe'],
                ['code' => 'SY', 'name' => 'Syria', 'flag_emoji' => '🇸🇾', 'capital' => 'Damascus', 'region' => 'Asia'],
                ['code' => 'TW', 'name' => 'Taiwan', 'flag_emoji' => '🇹🇼', 'capital' => 'Taipei', 'region' => 'Asia'],
                ['code' => 'TJ', 'name' => 'Tajikistan', 'flag_emoji' => '🇹🇯', 'capital' => 'Dushanbe', 'region' => 'Asia'],
                ['code' => 'TZ', 'name' => 'Tanzania', 'flag_emoji' => '🇹🇿', 'capital' => 'Dodoma', 'region' => 'Africa'],
                ['code' => 'TH', 'name' => 'Thailand', 'flag_emoji' => '🇹🇭', 'capital' => 'Bangkok', 'region' => 'Asia'],
                ['code' => 'TL', 'name' => 'Timor-Leste', 'flag_emoji' => '🇹🇱', 'capital' => 'Dili', 'region' => 'Asia'],
                ['code' => 'TG', 'name' => 'Togo', 'flag_emoji' => '🇹🇬', 'capital' => 'Lomé', 'region' => 'Africa'],
                ['code' => 'TO', 'name' => 'Tonga', 'flag_emoji' => '🇹🇴', 'capital' => 'Nuku\'alofa', 'region' => 'Oceania'],
                ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'flag_emoji' => '🇹🇹', 'capital' => 'Port of Spain', 'region' => 'Americas'],
                ['code' => 'TN', 'name' => 'Tunisia', 'flag_emoji' => '🇹🇳', 'capital' => 'Tunis', 'region' => 'Africa'],
                ['code' => 'TR', 'name' => 'Turkey', 'flag_emoji' => '🇹🇷', 'capital' => 'Ankara', 'region' => 'Asia'],
                ['code' => 'TM', 'name' => 'Turkmenistan', 'flag_emoji' => '🇹🇲', 'capital' => 'Ashgabat', 'region' => 'Asia'],
                ['code' => 'TV', 'name' => 'Tuvalu', 'flag_emoji' => '🇹🇻', 'capital' => 'Funafuti', 'region' => 'Oceania'],
                ['code' => 'UG', 'name' => 'Uganda', 'flag_emoji' => '🇺🇬', 'capital' => 'Kampala', 'region' => 'Africa'],
                ['code' => 'UA', 'name' => 'Ukraine', 'flag_emoji' => '🇺🇦', 'capital' => 'Kyiv', 'region' => 'Europe'],
                ['code' => 'AE', 'name' => 'United Arab Emirates', 'flag_emoji' => '🇦🇪', 'capital' => 'Abu Dhabi', 'region' => 'Asia'],
                ['code' => 'GB', 'name' => 'United Kingdom', 'flag_emoji' => '🇬🇧', 'capital' => 'London', 'region' => 'Europe'],
                ['code' => 'US', 'name' => 'United States', 'flag_emoji' => '🇺🇸', 'capital' => 'Washington D.C.', 'region' => 'Americas'],
                ['code' => 'UY', 'name' => 'Uruguay', 'flag_emoji' => '🇺🇾', 'capital' => 'Montevideo', 'region' => 'Americas'],
                ['code' => 'UZ', 'name' => 'Uzbekistan', 'flag_emoji' => '🇺🇿', 'capital' => 'Tashkent', 'region' => 'Asia'],
                ['code' => 'VU', 'name' => 'Vanuatu', 'flag_emoji' => '🇻🇺', 'capital' => 'Port Vila', 'region' => 'Oceania'],
                ['code' => 'VE', 'name' => 'Venezuela', 'flag_emoji' => '🇻🇪', 'capital' => 'Caracas', 'region' => 'Americas'],
                ['code' => 'VN', 'name' => 'Vietnam', 'flag_emoji' => '🇻🇳', 'capital' => 'Hanoi', 'region' => 'Asia'],
                ['code' => 'YE', 'name' => 'Yemen', 'flag_emoji' => '🇾🇪', 'capital' => 'Sana\'a', 'region' => 'Asia'],
                ['code' => 'ZM', 'name' => 'Zambia', 'flag_emoji' => '🇿🇲', 'capital' => 'Lusaka', 'region' => 'Africa'],
                ['code' => 'ZW', 'name' => 'Zimbabwe', 'flag_emoji' => '🇿🇼', 'capital' => 'Harare', 'region' => 'Africa'],
            ];
        }

        return response()->json(['countries' => $countries]);
    }
}

            ['code' => 'AD', 'name' => 'Andorra', 'flag_emoji' => '🇦🇩'],
            ['code' => 'AO', 'name' => 'Angola', 'flag_emoji' => '🇦🇴'],
            ['code' => 'AG', 'name' => 'Antigua and Barbuda', 'flag_emoji' => '🇦🇬'],
            ['code' => 'AR', 'name' => 'Argentina', 'flag_emoji' => '🇦🇷'],
            ['code' => 'AM', 'name' => 'Armenia', 'flag_emoji' => '🇦🇲'],
            ['code' => 'AU', 'name' => 'Australia', 'flag_emoji' => '🇦🇺'],
            ['code' => 'AT', 'name' => 'Austria', 'flag_emoji' => '🇦🇹'],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'flag_emoji' => '🇦🇿'],
            ['code' => 'BS', 'name' => 'Bahamas', 'flag_emoji' => '🇧🇸'],
            ['code' => 'BH', 'name' => 'Bahrain', 'flag_emoji' => '🇧🇭'],
            ['code' => 'BD', 'name' => 'Bangladesh', 'flag_emoji' => '🇧🇩'],
            ['code' => 'BB', 'name' => 'Barbados', 'flag_emoji' => '🇧🇧'],
            ['code' => 'BY', 'name' => 'Belarus', 'flag_emoji' => '🇧🇾'],
            ['code' => 'BE', 'name' => 'Belgium', 'flag_emoji' => '🇧🇪'],
            ['code' => 'BZ', 'name' => 'Belize', 'flag_emoji' => '🇧🇿'],
            ['code' => 'BJ', 'name' => 'Benin', 'flag_emoji' => '🇧🇯'],
            ['code' => 'BT', 'name' => 'Bhutan', 'flag_emoji' => '🇧🇹'],
            ['code' => 'BO', 'name' => 'Bolivia', 'flag_emoji' => '🇧🇴'],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'flag_emoji' => '🇧🇦'],
            ['code' => 'BW', 'name' => 'Botswana', 'flag_emoji' => '🇧🇼'],
            ['code' => 'BR', 'name' => 'Brazil', 'flag_emoji' => '🇧🇷'],
            ['code' => 'BN', 'name' => 'Brunei', 'flag_emoji' => '🇧🇳'],
            ['code' => 'BG', 'name' => 'Bulgaria', 'flag_emoji' => '🇧🇬'],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'flag_emoji' => '🇧🇫'],
            ['code' => 'BI', 'name' => 'Burundi', 'flag_emoji' => '🇧🇮'],
            ['code' => 'KH', 'name' => 'Cambodia', 'flag_emoji' => '🇰🇭'],
            ['code' => 'CM', 'name' => 'Cameroon', 'flag_emoji' => '🇨🇲'],
            ['code' => 'CA', 'name' => 'Canada', 'flag_emoji' => '🇨🇦'],
            ['code' => 'CV', 'name' => 'Cape Verde', 'flag_emoji' => '🇨🇻'],
            ['code' => 'CF', 'name' => 'Central African Republic', 'flag_emoji' => '🇨🇫'],
            ['code' => 'TD', 'name' => 'Chad', 'flag_emoji' => '🇹🇩'],
            ['code' => 'CL', 'name' => 'Chile', 'flag_emoji' => '🇨🇱'],
            ['code' => 'CN', 'name' => 'China', 'flag_emoji' => '🇨🇳'],
            ['code' => 'CO', 'name' => 'Colombia', 'flag_emoji' => '🇨🇴'],
            ['code' => 'KM', 'name' => 'Comoros', 'flag_emoji' => '🇰🇲'],
            ['code' => 'CG', 'name' => 'Congo', 'flag_emoji' => '🇨🇬'],
            ['code' => 'CD', 'name' => 'Democratic Republic of the Congo', 'flag_emoji' => '🇨🇩'],
            ['code' => 'CR', 'name' => 'Costa Rica', 'flag_emoji' => '🇨🇷'],
            ['code' => 'HR', 'name' => 'Croatia', 'flag_emoji' => '🇭🇷'],
            ['code' => 'CU', 'name' => 'Cuba', 'flag_emoji' => '🇨🇺'],
            ['code' => 'CY', 'name' => 'Cyprus', 'flag_emoji' => '🇨🇾'],
            ['code' => 'CZ', 'name' => 'Czech Republic', 'flag_emoji' => '🇨🇿'],
            ['code' => 'DK', 'name' => 'Denmark', 'flag_emoji' => '🇩🇰'],
            ['code' => 'DJ', 'name' => 'Djibouti', 'flag_emoji' => '🇩🇯'],
            ['code' => 'DM', 'name' => 'Dominica', 'flag_emoji' => '🇩🇲'],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'flag_emoji' => '🇩🇴'],
            ['code' => 'EC', 'name' => 'Ecuador', 'flag_emoji' => '🇪🇨'],
            ['code' => 'EG', 'name' => 'Egypt', 'flag_emoji' => '🇪🇬'],
            ['code' => 'SV', 'name' => 'El Salvador', 'flag_emoji' => '🇸🇻'],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'flag_emoji' => '🇬🇶'],
            ['code' => 'ER', 'name' => 'Eritrea', 'flag_emoji' => '🇪🇷'],
            ['code' => 'EE', 'name' => 'Estonia', 'flag_emoji' => '🇪🇪'],
            ['code' => 'ET', 'name' => 'Ethiopia', 'flag_emoji' => '🇪🇹'],
            ['code' => 'FJ', 'name' => 'Fiji', 'flag_emoji' => '🇫🇯'],
            ['code' => 'FI', 'name' => 'Finland', 'flag_emoji' => '🇫🇮'],
            ['code' => 'FR', 'name' => 'France', 'flag_emoji' => '🇫🇷'],
            ['code' => 'GA', 'name' => 'Gabon', 'flag_emoji' => '🇬🇦'],
            ['code' => 'GM', 'name' => 'Gambia', 'flag_emoji' => '🇬🇲'],
            ['code' => 'GE', 'name' => 'Georgia', 'flag_emoji' => '🇬🇪'],
            ['code' => 'DE', 'name' => 'Germany', 'flag_emoji' => '🇩🇪'],
            ['code' => 'GH', 'name' => 'Ghana', 'flag_emoji' => '🇬🇭'],
            ['code' => 'GR', 'name' => 'Greece', 'flag_emoji' => '🇬🇷'],
            ['code' => 'GD', 'name' => 'Grenada', 'flag_emoji' => '🇬🇩'],
            ['code' => 'GT', 'name' => 'Guatemala', 'flag_emoji' => '🇬🇹'],
            ['code' => 'GN', 'name' => 'Guinea', 'flag_emoji' => '🇬🇳'],
            ['code' => 'GW', 'name' => 'Guinea-Bissau', 'flag_emoji' => '🇬🇼'],
            ['code' => 'GY', 'name' => 'Guyana', 'flag_emoji' => '🇬🇾'],
            ['code' => 'HT', 'name' => 'Haiti', 'flag_emoji' => '🇭🇹'],
            ['code' => 'HN', 'name' => 'Honduras', 'flag_emoji' => '🇭🇳'],
            ['code' => 'HU', 'name' => 'Hungary', 'flag_emoji' => '🇭🇺'],
            ['code' => 'IS', 'name' => 'Iceland', 'flag_emoji' => '🇮🇸'],
            ['code' => 'IN', 'name' => 'India', 'flag_emoji' => '🇮🇳'],
            ['code' => 'ID', 'name' => 'Indonesia', 'flag_emoji' => '🇮🇩'],
            ['code' => 'IR', 'name' => 'Iran', 'flag_emoji' => '🇮🇷'],
            ['code' => 'IQ', 'name' => 'Iraq', 'flag_emoji' => '🇮🇶'],
            ['code' => 'IE', 'name' => 'Ireland', 'flag_emoji' => '🇮🇪'],
            ['code' => 'IL', 'name' => 'Israel', 'flag_emoji' => '🇮🇱'],
            ['code' => 'IT', 'name' => 'Italy', 'flag_emoji' => '🇮🇹'],
            ['code' => 'CI', 'name' => 'Ivory Coast', 'flag_emoji' => '🇨🇮'],
            ['code' => 'JM', 'name' => 'Jamaica', 'flag_emoji' => '🇯🇲'],
            ['code' => 'JP', 'name' => 'Japan', 'flag_emoji' => '🇯🇵'],
            ['code' => 'JO', 'name' => 'Jordan', 'flag_emoji' => '🇯🇴'],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'flag_emoji' => '🇰🇿'],
            ['code' => 'KE', 'name' => 'Kenya', 'flag_emoji' => '🇰🇪'],
            ['code' => 'KI', 'name' => 'Kiribati', 'flag_emoji' => '🇰🇮'],
            ['code' => 'KP', 'name' => 'North Korea', 'flag_emoji' => '🇰🇵'],
            ['code' => 'KR', 'name' => 'South Korea', 'flag_emoji' => '🇰🇷'],
            ['code' => 'KW', 'name' => 'Kuwait', 'flag_emoji' => '🇰🇼'],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'flag_emoji' => '🇰🇬'],
            ['code' => 'LA', 'name' => 'Laos', 'flag_emoji' => '🇱🇦'],
            ['code' => 'LV', 'name' => 'Latvia', 'flag_emoji' => '🇱🇻'],
            ['code' => 'LB', 'name' => 'Lebanon', 'flag_emoji' => '🇱🇧'],
            ['code' => 'LS', 'name' => 'Lesotho', 'flag_emoji' => '🇱🇸'],
            ['code' => 'LR', 'name' => 'Liberia', 'flag_emoji' => '🇱🇷'],
            ['code' => 'LY', 'name' => 'Libya', 'flag_emoji' => '🇱🇾'],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'flag_emoji' => '🇱🇮'],
            ['code' => 'LT', 'name' => 'Lithuania', 'flag_emoji' => '🇱🇹'],
            ['code' => 'LU', 'name' => 'Luxembourg', 'flag_emoji' => '🇱🇺'],
            ['code' => 'MG', 'name' => 'Madagascar', 'flag_emoji' => '🇲🇬'],
            ['code' => 'MW', 'name' => 'Malawi', 'flag_emoji' => '🇲🇼'],
            ['code' => 'MY', 'name' => 'Malaysia', 'flag_emoji' => '🇲🇾'],
            ['code' => 'MV', 'name' => 'Maldives', 'flag_emoji' => '🇲🇻'],
            ['code' => 'ML', 'name' => 'Mali', 'flag_emoji' => '🇲🇱'],
            ['code' => 'MT', 'name' => 'Malta', 'flag_emoji' => '🇲🇹'],
            ['code' => 'MH', 'name' => 'Marshall Islands', 'flag_emoji' => '🇲🇭'],
            ['code' => 'MR', 'name' => 'Mauritania', 'flag_emoji' => '🇲🇷'],
            ['code' => 'MU', 'name' => 'Mauritius', 'flag_emoji' => '🇲🇺'],
            ['code' => 'MX', 'name' => 'Mexico', 'flag_emoji' => '🇲🇽'],
            ['code' => 'FM', 'name' => 'Micronesia', 'flag_emoji' => '🇫🇲'],
            ['code' => 'MD', 'name' => 'Moldova', 'flag_emoji' => '🇲🇩'],
            ['code' => 'MC', 'name' => 'Monaco', 'flag_emoji' => '🇲🇨'],
            ['code' => 'MN', 'name' => 'Mongolia', 'flag_emoji' => '🇲🇳'],
            ['code' => 'ME', 'name' => 'Montenegro', 'flag_emoji' => '🇲🇪'],
            ['code' => 'MA', 'name' => 'Morocco', 'flag_emoji' => '🇲🇦'],
            ['code' => 'MZ', 'name' => 'Mozambique', 'flag_emoji' => '🇲🇿'],
            ['code' => 'MM', 'name' => 'Myanmar', 'flag_emoji' => '🇲🇲'],
            ['code' => 'NA', 'name' => 'Namibia', 'flag_emoji' => '🇳🇦'],
            ['code' => 'NR', 'name' => 'Nauru', 'flag_emoji' => '🇳🇷'],
            ['code' => 'NP', 'name' => 'Nepal', 'flag_emoji' => '🇳🇵'],
            ['code' => 'NL', 'name' => 'Netherlands', 'flag_emoji' => '🇳🇱'],
            ['code' => 'NZ', 'name' => 'New Zealand', 'flag_emoji' => '🇳🇿'],
            ['code' => 'NI', 'name' => 'Nicaragua', 'flag_emoji' => '🇳🇮'],
            ['code' => 'NE', 'name' => 'Niger', 'flag_emoji' => '🇳🇪'],
            ['code' => 'NG', 'name' => 'Nigeria', 'flag_emoji' => '🇳🇬'],
            ['code' => 'NO', 'name' => 'Norway', 'flag_emoji' => '🇳🇴'],
            ['code' => 'OM', 'name' => 'Oman', 'flag_emoji' => '🇴🇲'],
            ['code' => 'PK', 'name' => 'Pakistan', 'flag_emoji' => '🇵🇰'],
            ['code' => 'PW', 'name' => 'Palau', 'flag_emoji' => '🇵🇼'],
            ['code' => 'PS', 'name' => 'Palestine', 'flag_emoji' => '🇵🇸'],
            ['code' => 'PA', 'name' => 'Panama', 'flag_emoji' => '🇵🇦'],
            ['code' => 'PG', 'name' => 'Papua New Guinea', 'flag_emoji' => '🇵🇬'],
            ['code' => 'PY', 'name' => 'Paraguay', 'flag_emoji' => '🇵🇾'],
            ['code' => 'PE', 'name' => 'Peru', 'flag_emoji' => '🇵🇪'],
            ['code' => 'PH', 'name' => 'Philippines', 'flag_emoji' => '🇵🇭'],
            ['code' => 'PL', 'name' => 'Poland', 'flag_emoji' => '🇵🇱'],
            ['code' => 'PT', 'name' => 'Portugal', 'flag_emoji' => '🇵🇹'],
            ['code' => 'QA', 'name' => 'Qatar', 'flag_emoji' => '🇶🇦'],
            ['code' => 'RO', 'name' => 'Romania', 'flag_emoji' => '🇷🇴'],
            ['code' => 'RU', 'name' => 'Russia', 'flag_emoji' => '🇷🇺'],
            ['code' => 'RW', 'name' => 'Rwanda', 'flag_emoji' => '🇷🇼'],
            ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'flag_emoji' => '🇰🇳'],
            ['code' => 'LC', 'name' => 'Saint Lucia', 'flag_emoji' => '🇱🇨'],
            ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'flag_emoji' => '🇻🇨'],
            ['code' => 'WS', 'name' => 'Samoa', 'flag_emoji' => '🇼🇸'],
            ['code' => 'SM', 'name' => 'San Marino', 'flag_emoji' => '🇸🇲'],
            ['code' => 'ST', 'name' => 'Sao Tome and Principe', 'flag_emoji' => '🇸🇹'],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'flag_emoji' => '🇸🇦'],
            ['code' => 'SN', 'name' => 'Senegal', 'flag_emoji' => '🇸🇳'],
            ['code' => 'RS', 'name' => 'Serbia', 'flag_emoji' => '🇷🇸'],
            ['code' => 'SC', 'name' => 'Seychelles', 'flag_emoji' => '🇸🇨'],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'flag_emoji' => '🇸🇱'],
            ['code' => 'SG', 'name' => 'Singapore', 'flag_emoji' => '🇸🇬'],
            ['code' => 'SK', 'name' => 'Slovakia', 'flag_emoji' => '🇸🇰'],
            ['code' => 'SI', 'name' => 'Slovenia', 'flag_emoji' => '🇸🇮'],
            ['code' => 'SB', 'name' => 'Solomon Islands', 'flag_emoji' => '🇸🇧'],
            ['code' => 'SO', 'name' => 'Somalia', 'flag_emoji' => '🇸🇴'],
            ['code' => 'ZA', 'name' => 'South Africa', 'flag_emoji' => '🇿🇦'],
            ['code' => 'SS', 'name' => 'South Sudan', 'flag_emoji' => '🇸🇸'],
            ['code' => 'ES', 'name' => 'Spain', 'flag_emoji' => '🇪🇸'],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'flag_emoji' => '🇱🇰'],
            ['code' => 'SD', 'name' => 'Sudan', 'flag_emoji' => '🇸🇩'],
            ['code' => 'SR', 'name' => 'Suriname', 'flag_emoji' => '🇸🇷'],
            ['code' => 'SE', 'name' => 'Sweden', 'flag_emoji' => '🇸🇪'],
            ['code' => 'CH', 'name' => 'Switzerland', 'flag_emoji' => '🇨🇭'],
            ['code' => 'SY', 'name' => 'Syria', 'flag_emoji' => '🇸🇾'],
            ['code' => 'TW', 'name' => 'Taiwan', 'flag_emoji' => '🇹🇼'],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'flag_emoji' => '🇹🇯'],
            ['code' => 'TZ', 'name' => 'Tanzania', 'flag_emoji' => '🇹🇿'],
            ['code' => 'TH', 'name' => 'Thailand', 'flag_emoji' => '🇹🇭'],
            ['code' => 'TL', 'name' => 'Timor-Leste', 'flag_emoji' => '🇹🇱'],
            ['code' => 'TG', 'name' => 'Togo', 'flag_emoji' => '🇹🇬'],
            ['code' => 'TO', 'name' => 'Tonga', 'flag_emoji' => '🇹🇴'],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'flag_emoji' => '🇹🇹'],
            ['code' => 'TN', 'name' => 'Tunisia', 'flag_emoji' => '🇹🇳'],
            ['code' => 'TR', 'name' => 'Turkey', 'flag_emoji' => '🇹🇷'],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'flag_emoji' => '🇹🇲'],
            ['code' => 'TV', 'name' => 'Tuvalu', 'flag_emoji' => '🇹🇻'],
            ['code' => 'UG', 'name' => 'Uganda', 'flag_emoji' => '🇺🇬'],
            ['code' => 'UA', 'name' => 'Ukraine', 'flag_emoji' => '🇺🇦'],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'flag_emoji' => '🇦🇪'],
            ['code' => 'GB', 'name' => 'United Kingdom', 'flag_emoji' => '🇬🇧'],
            ['code' => 'US', 'name' => 'United States', 'flag_emoji' => '🇺🇸'],
            ['code' => 'UY', 'name' => 'Uruguay', 'flag_emoji' => '🇺🇾'],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'flag_emoji' => '🇺🇿'],
            ['code' => 'VU', 'name' => 'Vanuatu', 'flag_emoji' => '🇻🇺'],
            ['code' => 'VE', 'name' => 'Venezuela', 'flag_emoji' => '🇻🇪'],
            ['code' => 'VN', 'name' => 'Vietnam', 'flag_emoji' => '🇻🇳'],
            ['code' => 'YE', 'name' => 'Yemen', 'flag_emoji' => '🇾🇪'],
            ['code' => 'ZM', 'name' => 'Zambia', 'flag_emoji' => '🇿🇲'],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'flag_emoji' => '🇿🇼'],
        ];

        return response()->json(['countries' => $countries]);
    }
}
