import json
import os

all_cities_data = {
    "alb": [{"p": "کرج", "e": "Karaj"}, {"p": "فردیس", "e": "Fardis"}, {"p": "کمال‌شهر", "e": "Kamal Shahr"}, {"p": "نظرآباد", "e": "Nazarabad"}, {"p": "محمدشهر", "e": "Mahammadshahr"}, {"p": "ماهدشت", "e": "Mahdasht"}, {"p": "مشکین‌دشت", "e": "Meshkin Dasht"}, {"p": "هشتگرد", "e": "Hashtgerd"}, {"p": "چهارباغ", "e": "Chaharbagh"}, {"p": "شهر جدید هشتگرد", "e": "New Hashtgerd"}, {"p": "اشتهارد", "e": "Eshtehard"}, {"p": "گرمدره", "e": "Garmdarreh"}, {"p": "گلسار", "e": "Golsar"}, {"p": "کوهسار", "e": "Kuhsar"}, {"p": "تنکمان", "e": "Tankaman"}, {"p": "طالقان", "e": "Taleqan"}, {"p": "پلنگ‌آباد", "e": "Palangabad"}, {"p": "آسارا", "e": "Asara"}],
    "ard": [{"p": "اردبیل", "e": "Ardabil"}, {"p": "پارس‌آباد", "e": "Parsabad"}, {"p": "مشگین‌شهر", "e": "Meshgin Shahr"}, {"p": "خلخال", "e": "Khalkhal"}, {"p": "گرمی", "e": "Germi"}, {"p": "نمین", "e": "Namin"}, {"p": "بیله‌سوار", "e": "Bileh Savar"}, {"p": "اصلاندوز", "e": "Aslan Duz"}, {"p": "کوثر", "e": "Kowsar"}, {"p": "نیر", "e": "Nir"}, {"p": "سرعین", "e": "Sareyn"}, {"p": "انگوت", "e": "Angut"}],
    "azg": [{"p": "تبریز", "e": "Tabriz"}, {"p": "مراغه", "e": "Maragheh"}, {"p": "مرند", "e": "Marand"}, {"p": "اهر", "e": "Ahar"}, {"p": "میانه", "e": "Mianeh"}, {"p": "بناب", "e": "Bonab"}, {"p": "سهند", "e": "Sahand"}, {"p": "سراب", "e": "Sarab"}, {"p": "آذرشهر", "e": "Azarshahr"}, {"p": "هادیشهر", "e": "Hadishahr"}, {"p": "عجب‌شیر", "e": "Ajab Shir"}, {"p": "سردرود", "e": "Sardrud"}, {"p": "ملکان", "e": "Malekan"}, {"p": "شبستر", "e": "Shabestar"}, {"p": "خسروشاه", "e": "Khosrowshah"}, {"p": "بستان‌آباد", "e": "Bostanabad"}, {"p": "هشترود", "e": "Hashtrud"}, {"p": "اسکو", "e": "Osku"}, {"p": "ایلخچی", "e": "Ilkhichi"}, {"p": "ممقان", "e": "Mamaghan"}, {"p": "گوگان", "e": "Gogan"}, {"p": "بخشایش", "e": "Bakhshayesh"}, {"p": "قره‌آغاج", "e": "Qarah Aghaj"}, {"p": "مهربان", "e": "Mehraban"}, {"p": "تیمورلو", "e": "Teymurlu"}, {"p": "شربیان", "e": "Sharabian"}],
    "azs": [{"p": "ارومیه", "e": "Urmia"}, {"p": "خوی", "e": "Khoy"}, {"p": "بوکان", "e": "Bukan"}, {"p": "مهاباد", "e": "Mahabad"}, {"p": "میاندوآب", "e": "Miandoab"}, {"p": "سلماس", "e": "Salmas"}, {"p": "پیرانشهر", "e": "Piranshahr"}, {"p": "نقده", "e": "Naqadeh"}, {"p": "تکاب", "e": "Takab"}, {"p": "ماکو", "e": "Maku"}, {"p": "سردشت", "e": "Sardasht"}, {"p": "شاهین‌دژ", "e": "Shahindezh"}, {"p": "اشنویه", "e": "Oshnavieh"}, {"p": "قره‌ضیاءالدین", "e": "Qarah Ziyaoddin"}, {"p": "شوط", "e": "Showt"}, {"p": "سیه‌چشمه", "e": "Siyah Cheshmeh"}, {"p": "ربط", "e": "Rabat"}, {"p": "پلدشت", "e": "Poldasht"}],
    "bus": [{"p": "بوشهر", "e": "Bushehr"}, {"p": "برازجان", "e": "Borazjan"}, {"p": "بندر گناوه", "e": "Bandar Ganaveh"}, {"p": "بندر کنگان", "e": "Bandar Kangan"}, {"p": "خورموج", "e": "Khormuj"}, {"p": "جم", "e": "Jam"}, {"p": "بندر دیلم", "e": "Bandar Dayyer"}, {"p": "عسلویه", "e": "Assaluyeh"}, {"p": "آب‌پخش", "e": "Ab Pakhsh"}, {"p": "دیر", "e": "Dayyer"}, {"p": "چغادک", "e": "Choghadak"}, {"p": "اهرم", "e": "Ahram"}],
    "chb": [{"p": "شهرکرد", "e": "Shahrekord"}, {"p": "بروجن", "e": "Borujen"}, {"p": "لردگان", "e": "Lordegan"}, {"p": "فرخ‌شهر", "e": "Farrokh Shahr"}, {"p": "فارسان", "e": "Farsan"}, {"p": "هفشجان", "e": "Hafshejan"}, {"p": "جونقان", "e": "Juneqan"}, {"p": "بن", "e": "Ben"}, {"p": "کیان", "e": "Kian"}, {"p": "سورشجان", "e": "Soreshjan"}, {"p": "بلداجی", "e": "Boldaji"}, {"p": "باباحیدر", "e": "Babahaydar"}, {"p": "اردل", "e": "Ardal"}],
    "khs": [{"p": "بیرجند", "e": "Birjand"}, {"p": "قائن", "e": "Qaen"}, {"p": "طبس", "e": "Tabas"}, {"p": "فردوس", "e": "Ferdows"}, {"p": "نهبندان", "e": "Nehbandan"}, {"p": "بشرویه", "e": "Boshruyeh"}, {"p": "سرایان", "e": "Sarayan"}, {"p": "سربیشه", "e": "Sarbisheh"}, {"p": "اسلامیه", "e": "Islamiyeh"}, {"p": "حاجی‌آباد", "e": "Hajjiabad"}, {"p": "خضری دشت‌بیاض", "e": "Khezri Dasht-e Bayaz"}],
    "khr": [{"p": "مشهد", "e": "Mashhad"}, {"p": "نیشابور", "e": "Neyshabur"}, {"p": "سبزوار", "e": "Sabzevar"}, {"p": "تربت حیدریه", "e": "Torbat-e Heydarieh"}, {"p": "کاشمر", "e": "Kashmar"}, {"p": "قوچان", "e": "Quchan"}, {"p": "تربت جام", "e": "Torbat-e Jam"}, {"p": "تایباد", "e": "Taybad"}, {"p": "چناران", "e": "Chenaran"}, {"p": "سرخس", "e": "Sarakhs"}, {"p": "گناباد", "e": "Gonabad"}, {"p": "فریمان", "e": "Fariman"}, {"p": "گلبهار", "e": "Golbahar"}, {"p": "درگز", "e": "Dargaz"}, {"p": "خواف", "e": "Khaf"}, {"p": "بردسکن", "e": "Bardaskan"}, {"p": "طرقبه", "e": "Torqabeh"}, {"p": "فیض‌آباد", "e": "Feyzabad"}, {"p": "نقاب", "e": "Noqab"}, {"p": "شاندیز", "e": "Shandiz"}, {"p": "خلیل‌آباد", "e": "Khalilabad"}],
    "khn": [{"p": "بجنورد", "e": "Bojnord"}, {"p": "شیروان", "e": "Shirvan"}, {"p": "اسفراین", "e": "Esfarayen"}, {"p": "آشخانه", "e": "Ashkhaneh"}, {"p": "جاجرم", "e": "Jajarm"}, {"p": "فاروج", "e": "Faruj"}, {"p": "گرمه", "e": "Garmeh"}, {"p": "راز", "e": "Raz"}, {"p": "تیتکانلو", "e": "Titkanlu"}, {"p": "صفی‌آباد", "e": "Safiabad"}],
    "khu": [{"p": "اهواز", "e": "Ahvaz"}, {"p": "دزفول", "e": "Dezful"}, {"p": "آبادان", "e": "Abadan"}, {"p": "بندر ماهشهر", "e": "Bandar-e Mahshahr"}, {"p": "بهبهان", "e": "Behbahan"}, {"p": "ایذه", "e": "Izeh"}, {"p": "شوشتر", "e": "Shushtar"}, {"p": "اندیمشک", "e": "Andimeshk"}, {"p": "خرمشهر", "e": "Khorramshahr"}, {"p": "شوش", "e": "Shush"}, {"p": "مسجدسلیمان", "e": "Masjed Soleyman"}, {"p": "بندر امام خمینی", "e": "Bandar-e Emam Khomeyni"}, {"p": "رامهرمز", "e": "Ramhormoz"}, {"p": "امیدیه", "e": "Omidiyeh"}, {"p": "کوت عبدالله", "e": "Kut-e Abdollah"}, {"p": "سوسنگرد", "e": "Susangerd"}, {"p": "شادگان", "e": "Shadegan"}, {"p": "شیبان", "e": "Sheyban"}, {"p": "باغ‌ملک", "e": "Bagh-e Malek"}],
    "qom": [{"p": "قم", "e": "Qom"}, {"p": "قنوات", "e": "Qanavat"}, {"p": "جعفریه", "e": "Jafariyeh"}, {"p": "کهک", "e": "Kahak"}, {"p": "دستجرد", "e": "Dastjerd"}, {"p": "سلفچگان", "e": "Salafchegan"}],
    "teh": [{"p": "تهران", "e": "Tehran"}, {"p": "اسلام‌شهر", "e": "Islamshahr"}, {"p": "شهریار", "e": "Shahriar"}, {"p": "قدس", "e": "Qods"}, {"p": "ملارد", "e": "Malard"}, {"p": "صالحیه", "e": "Salehiyeh"}, {"p": "پاکدشت", "e": "Pakdasht"}, {"p": "قرچک", "e": "Qarchak"}, {"p": "ورامین", "e": "Varamin"}, {"p": "گلستان", "e": "Golestan"}, {"p": "ری", "e": "Ray"}, {"p": "اندیشه", "e": "Andisheh"}, {"p": "رباط‌کریم", "e": "Robat Karim"}, {"p": "پردیس", "e": "Pardis"}, {"p": "باقرشهر", "e": "Baqershahr"}, {"p": "بومهن", "e": "Bumehen"}, {"p": "پیشوا", "e": "Pishva"}, {"p": "نسیم‌شهر", "e": "Nasimshahr"}, {"p": "صباشهر", "e": "Sabashahr"}, {"p": "چهاردانگه", "e": "Chahardangeh"}, {"p": "دماوند", "e": "Damavand"}, {"p": "حسن‌آباد", "e": "Hasanabad"}, {"p": "باقرشهر", "e": "Baqershahr"}, {"p": "کهریزک", "e": "Kahrizak"}, {"p": "فردوسیه", "e": "Ferdowsieh"}, {"p": "وحیدیه", "e": "Vahidieh"}, {"p": "نصیرشهر", "e": "Nasirshahr"}, {"p": "رودهن", "e": "Rudehen"}, {"p": "شاهدشهر", "e": "Shahedshahr"}, {"p": "صفادشت", "e": "Safadasht"}, {"p": "فیروزکوه", "e": "Firuzkuh"}, {"p": "لواسان", "e": "Lavasan"}, {"p": "آبسرد", "e": "Absard"}, {"p": "شریف‌آباد", "e": "Sharifabad"}, {"p": "نجم‌آباد", "e": "Najmabad"}, {"p": "ارجمند", "e": "Arjmand"}],
    "qaz": [{"p": "قزوین", "e": "Qazvin"}, {"p": "الوند", "e": "Alvand"}, {"p": "محمدیه", "e": "Mohammadieh"}, {"p": "تاکستان", "e": "Takestan"}, {"p": "آبیک", "e": "Abyek"}, {"p": "اقبالیه", "e": "Eqbalieh"}, {"p": "محمودآباد نمونه", "e": "Mahmudabad Nemuneh"}, {"p": "بویین‌زهرا", "e": "Buin Zahra"}, {"p": "شریفیه", "e": "Sharifieh"}, {"p": "بیدستان", "e": "Bidestan"}, {"p": "ارداق", "e": "Ardaq"}, {"p": "آوج", "e": "Avaj"}, {"p": "شال", "e": "Shal"}, {"p": "اسفرورین", "e": "Esfarvarin"}, {"p": "ضیاءآباد", "e": "Ziaabad"}, {"p": "خرمدشت", "e": "Khorramdasht"}, {"p": "نرجه", "e": "Narjeh"}, {"p": "سگزآباد", "e": "Sagzabad"}, {"p": "سیردان", "e": "Sirdan"}, {"p": "رازمیان", "e": "Razmian"}, {"p": "معلم‌کلایه", "e": "Moallem Kalayeh"}, {"p": "کوهین", "e": "Kuhin"}],
    "zan": [{"p": "زنجان", "e": "Zanjan"}, {"p": "ابهر", "e": "Abhar"}, {"p": "خرمدره", "e": "Khorramdarreh"}, {"p": "قیدار", "e": "Qeydar"}, {"p": "هیدج", "e": "Hidaj"}, {"p": "صائین‌قلعه", "e": "Sain Qaleh"}, {"p": "آب‌بر", "e": "Abbar"}, {"p": "سلطانیه", "e": "Soltaniyeh"}, {"p": "سجاس", "e": "Sojas"}, {"p": "ماهنشان", "e": "Mah Neshan"}, {"p": "سهرورد", "e": "Sohrevard"}, {"p": "زرین‌آباد", "e": "Zarrin Abad"}, {"p": "نوربهار", "e": "Nurbahar"}, {"p": "کرسف", "e": "Karasf"}, {"p": "گرماب", "e": "Garmab"}, {"p": "دندی", "e": "Dandi"}, {"p": "چورزق", "e": "Chavarzaq"}, {"p": "حلب", "e": "Halab"}, {"p": "نیکپی", "e": "Nik Pey"}, {"p": "ارمغان‌خانه", "e": "Armaghan Khaneh"}],
    "far": [{"p": "شیراز", "e": "Shiraz"}, {"p": "مرودشت", "e": "Marvdasht"}, {"p": "جهرم", "e": "Jahrom"}, {"p": "فسا", "e": "Fasa"}, {"p": "داراب", "e": "Darab"}, {"p": "کازرون", "e": "Kazerun"}, {"p": "لار", "e": "Lar"}, {"p": "فیروزآباد", "e": "Firuzabad"}, {"p": "آباده", "e": "Abadeh"}, {"p": "نورآباد", "e": "Nurabad"}, {"p": "نی‌ریز", "e": "Neyriz"}, {"p": "اقلید", "e": "Eqlid"}, {"p": "استهبان", "e": "Estehban"}, {"p": "گراش", "e": "Gerash"}, {"p": "کوار", "e": "Kavar"}, {"p": "زرقان", "e": "Zarqan"}, {"p": "لامرد", "e": "Lamerd"}, {"p": "قائمیه", "e": "Qaemiyeh"}, {"p": "حاجی‌آباد", "e": "Hajiabad"}, {"p": "فراشبند", "e": "Farashband"}, {"p": "قیر", "e": "Qir"}, {"p": "اوز", "e": "Evaz"}, {"p": "خنج", "e": "Khonj"}, {"p": "خرامه", "e": "Kherameh"}, {"p": "سروستان", "e": "Sarvestan"}, {"p": "ارسنجان", "e": "Arsanjan"}, {"p": "سعادت‌شهر", "e": "Saadat Shahr"}, {"p": "قادرآباد", "e": "Qaderabad"}, {"p": "اردکان", "e": "Ardakan"}, {"p": "مصیری", "e": "Mosiri"}, {"p": "اشکنان", "e": "Ashkanan"}],
    "kor": [{"p": "سنندج", "e": "Sanandaj"}, {"p": "سقز", "e": "Saqqez"}, {"p": "مریوان", "e": "Marivan"}, {"p": "بانه", "e": "Baneh"}, {"p": "قروه", "e": "Qorveh"}, {"p": "کامیاران", "e": "Kamyaran"}, {"p": "بیجار", "e": "Bijar"}, {"p": "دیواندره", "e": "Divandarreh"}, {"p": "دهگلان", "e": "Dehgolan"}, {"p": "کانی‌دینار", "e": "Kani Dinar"}, {"p": "سریش‌آباد", "e": "Serishabad"}, {"p": "دلبران", "e": "Delbaran"}, {"p": "سروآباد", "e": "Sarvabad"}, {"p": "یاسوکند", "e": "Yasukand"}, {"p": "موچش", "e": "Muchesh"}, {"p": "بلبان‌آباد", "e": "Bolbanabad"}, {"p": "هورامان تخت", "e": "Hawraman Takht"}],
    "ker": [{"p": "کرمان", "e": "Kerman"}, {"p": "سیرجان", "e": "Sirjan"}, {"p": "رفسنجان", "e": "Rafsanjan"}, {"p": "جیرفت", "e": "Jiroft"}, {"p": "بم", "e": "Bam"}, {"p": "زرند", "e": "Zarand"}, {"p": "کهنوج", "e": "Kahnuj"}, {"p": "شهربابک", "e": "Shahr-e Babak"}, {"p": "بافت", "e": "Baft"}, {"p": "بردسیر", "e": "Bardsir"}, {"p": "بروات", "e": "Baravat"}, {"p": "راور", "e": "Ravar"}, {"p": "محمدآباد", "e": "Mohammadabad"}, {"p": "نجف‌شهر", "e": "Najafshahr"}, {"p": "ماهان", "e": "Mahan"}, {"p": "عنبرآباد", "e": "Anbarabad"}, {"p": "منوجان", "e": "Manujan"}, {"p": "انار", "e": "Anar"}, {"p": "رودبار", "e": "Rudbar"}, {"p": "رابر", "e": "Rabor"}, {"p": "قلعه‌گنج", "e": "Qaleh Ganj"}, {"p": "کوهبنان", "e": "Kuhbanan"}, {"p": "درب بهشت", "e": "Darb-e Behesht"}],
    "kms": [{"p": "کرمانشاه", "e": "Kermanshah"}, {"p": "اسلام‌آباد غرب", "e": "Islamabad-e Gharb"}, {"p": "جوانرود", "e": "Javanrud"}, {"p": "کنگاور", "e": "Kangavar"}, {"p": "سرپل ذهاب", "e": "Sarpol-e Zahab"}, {"p": "سنقر", "e": "Sonqor"}, {"p": "هرسین", "e": "Harsin"}, {"p": "صحنه", "e": "Sahneh"}, {"p": "پاوه", "e": "Paveh"}, {"p": "روانسر", "e": "Ravansar"}, {"p": "گیلانغرب", "e": "Gilan-e Gharb"}, {"p": "قصرشیرین", "e": "Qasr-e Shirin"}],
    "kba": [{"p": "یاسوج", "e": "Yasuj"}, {"p": "دوگنبدان", "e": "Dogonbadan"}, {"p": "دهدشت", "e": "Dehdasht"}, {"p": "لیکک", "e": "Likak"}, {"p": "مادوان", "e": "Madavan"}, {"p": "لنده", "e": "Landeh"}, {"p": "باشت", "e": "Basht"}, {"p": "سی‌سخت", "e": "Si Sakht"}, {"p": "سوق", "e": "Suq"}],
    "gol": [{"p": "گرگان", "e": "Gorgan"}, {"p": "گنبد کاووس", "e": "Gonbad-e Kavus"}, {"p": "بندر ترکمن", "e": "Bandar Torkaman"}, {"p": "علی‌آباد کتول", "e": "Aliabad-e Katul"}, {"p": "آزادشهر", "e": "Azadshahr"}, {"p": "کردکوی", "e": "Kordkuy"}, {"p": "کلاله", "e": "Kalaleh"}, {"p": "آق‌قلا", "e": "Aqqala"}, {"p": "مینودشت", "e": "Minudasht"}, {"p": "گالیکش", "e": "Galikesh"}, {"p": "بندر گز", "e": "Bandar Gaz"}, {"p": "فاضل‌آباد", "e": "Fazelabad"}, {"p": "گمیش‌تپه", "e": "Gomishan"}],
    "gil": [{"p": "رشت", "e": "Rasht"}, {"p": "بندر انزلی", "e": "Bandar-e Anzali"}, {"p": "لاهیجان", "e": "Lahijan"}, {"p": "لنگرود", "e": "Langarud"}, {"p": "هشتپر", "e": "Hashtpar"}, {"p": "آستارا", "e": "Astara"}, {"p": "صومعه‌سرا", "e": "Sowme'eh Sara"}, {"p": "آستانه اشرفیه", "e": "Astaneh-ye Ashrafiyeh"}, {"p": "رودسر", "e": "Rudsar"}, {"p": "فومن", "e": "Fuman"}, {"p": "خمام", "e": "Khomam"}, {"p": "سیاهکل", "e": "Siahkal"}, {"p": "رضوانشهر", "e": "Rezvanshahr"}, {"p": "ماسال", "e": "Masal"}, {"p": "منجیل", "e": "Manjil"}, {"p": "املش", "e": "Amlash"}, {"p": "کیاشهر", "e": "Kiashahr"}, {"p": "رستم‌آباد", "e": "Rostamabad"}, {"p": "لوشان", "e": "Lushan"}],
    "lor": [{"p": "خرم‌آباد", "e": "Khorramabad"}, {"p": "بروجرد", "e": "Borujerd"}, {"p": "دورود", "e": "Dorud"}, {"p": "کوهدشت", "e": "Kuhdasht"}, {"p": "الیگودرز", "e": "Aligudarz"}, {"p": "نورآباد", "e": "Nurabad"}, {"p": "ازنا", "e": "Azna"}, {"p": "الشتر", "e": "Alashtar"}, {"p": "پلدختر", "e": "Poldokhtar"}, {"p": "کونانی", "e": "Kounani"}, {"p": "معمولان", "e": "Mamulan"}],
    "maz": [{"p": "ساری", "e": "Sari"}, {"p": "بابل", "e": "Babol"}, {"p": "آمل", "e": "Amol"}, {"p": "قائم‌شهر", "e": "Qaem Shahr"}, {"p": "بهشهر", "e": "Behshahr"}, {"p": "چالوس", "e": "Chalus"}, {"p": "نکا", "e": "Neka"}, {"p": "بابلسر", "e": "Babolsar"}, {"p": "تنکابن", "e": "Tonekabon"}, {"p": "نوشهر", "e": "Nowshahr"}, {"p": "فریدونکنار", "e": "Fereydunkenar"}, {"p": "رامسر", "e": "Ramsar"}, {"p": "جویبار", "e": "Juybar"}, {"p": "محمودآباد", "e": "Mahmudabad"}, {"p": "نور", "e": "Nur"}],
    "mar": [{"p": "اراک", "e": "Arak"}, {"p": "ساوه", "e": "Saveh"}, {"p": "خمین", "e": "Khomeyn"}, {"p": "محلات", "e": "Mahallat"}, {"p": "دلیجان", "e": "Delijan"}, {"p": "کرهرود", "e": "Karharud"}, {"p": "شازند", "e": "Shazand"}, {"p": "مأمونیه", "e": "Mamuniyeh"}, {"p": "تفرش", "e": "Tafresh"}, {"p": "میلاجرد", "e": "Milajerd"}, {"p": "کمیجان", "e": "Komijan"}, {"p": "آشتیان", "e": "Ashtian"}],
    "hor": [{"p": "بندرعباس", "e": "Bandar Abbas"}, {"p": "میناب", "e": "Minab"}, {"p": "قشم", "e": "Qeshm"}, {"p": "کیش", "e": "Kish"}, {"p": "رودان", "e": "Rudan"}, {"p": "بندر لنگه", "e": "Bandar Lengeh"}, {"p": "حاجی‌آباد", "e": "Hajiabad"}, {"p": "جاسک", "e": "Jask"}, {"p": "بندر کنگ", "e": "Bandar Kong"}, {"p": "پارسیان", "e": "Parsian"}, {"p": "بستک", "e": "Bastak"}, {"p": "درگهان", "e": "Dargahan"}, {"p": "خمیر", "e": "Khamir"}],
    "ham": [{"p": "همدان", "e": "Hamadan"}, {"p": "ملایر", "e": "Malayer"}, {"p": "نهاوند", "e": "Nahavand"}, {"p": "اسدآباد", "e": "Asadabad"}, {"p": "تویسرکان", "e": "Tuyserkan"}, {"p": "بهار", "e": "Bahar"}, {"p": "کبودرآهنگ", "e": "Kabudarahang"}, {"p": "لالجین", "e": "Lalejin"}, {"p": "رزن", "e": "Razan"}, {"p": "فامنین", "e": "Famenin"}, {"p": "ازندریان", "e": "Azandarian"}, {"p": "مریانج", "e": "Maryanaj"}, {"p": "قروه درجزین", "e": "Qorveh-e Darjazin"}],
    "yaz": [{"p": "یزد", "e": "Yazd"}, {"p": "میبد", "e": "Meybod"}, {"p": "اردکان", "e": "Ardakan"}, {"p": "حمیدیا", "e": "Hamidiya"}, {"p": "بافق", "e": "Bafq"}, {"p": "مهریز", "e": "Mehriz"}, {"p": "ابرکوه", "e": "Abarkuh"}, {"p": "تفت", "e": "Taft"}, {"p": "شاهدیه", "e": "Shahediyeh"}, {"p": "زارچ", "e": "Zarch"}, {"p": "اشکذر", "e": "Ashkezar"}, {"p": "هرات", "e": "Herat"}],
    "sem": [{"p": "سمنان", "e": "Semnan"}, {"p": "شاهرود", "e": "Shahrud"}, {"p": "دامغان", "e": "Damghan"}, {"p": "گرمسار", "e": "Garmsar"}, {"p": "مهدی‌شهر", "e": "Mehdishahr"}, {"p": "ایوانکی", "e": "Eyvanki"}, {"p": "شهمیرزاد", "e": "Shahmirzad"}, {"p": "سرخه", "e": "Sorkheh"}, {"p": "مجت‌آباد", "e": "Mojtabad"}, {"p": "بسطام", "e": "Bastam"}, {"p": "آرادان", "e": "Aradan"}],
    "sab": [{"p": "زاهدان", "e": "Zahedan"}, {"p": "زابل", "e": "Zabol"}, {"p": "ایرانشهر", "e": "Iranshahr"}, {"p": "چابهار", "e": "Chabahar"}, {"p": "سراوان", "e": "Saravan"}, {"p": "خاش", "e": "Khash"}, {"p": "کنارک", "e": "Konarak"}, {"p": "جالق", "e": "Jalaq"}, {"p": "نیک‌شهر", "e": "Nikshahr"}, {"p": "پیشین", "e": "Pishin"}, {"p": "سوران", "e": "Suran"}, {"p": "زهک", "e": "Zehak"}, {"p": "فنوج", "e": "Fanuj"}, {"p": "مهرستان", "e": "Mehrestan"}, {"p": "بمپور", "e": "Bampur"}, {"p": "قصرقند", "e": "Qasre-Qand"}],
    "esf": [{"p": "اصفهان", "e": "Isfahan"}, {"p": "کاشان", "e": "Kashan"}, {"p": "خمینی‌شهر", "e": "Khomeyni Shahr"}, {"p": "نجف‌آباد", "e": "Najafabad"}, {"p": "شاهین‌شهر", "e": "Shahin Shahr"}, {"p": "شهرضا", "e": "Shahreza"}, {"p": "فولادشهر", "e": "Fuladshahr"}, {"p": "مبارکه", "e": "Mobarakeh"}, {"p": "آران و بیدگل", "e": "Aran va Bidgol"}, {"p": "گلپایگان", "e": "Golpayegan"}, {"p": "زرین‌شهر", "e": "Zarrin Shahr"}, {"p": "درچه", "e": "Dorcheh"}, {"p": "دولت‌آباد", "e": "Dowlatabad"}, {"p": "فلاورجان", "e": "Falavarjan"}, {"p": "قهدریجان", "e": "Qahderijan"}, {"p": "خورزوق", "e": "Khorzuq"}, {"p": "نائین", "e": "Nain"}, {"p": "سمیرم", "e": "Semirom"}, {"p": "داران", "e": "Daran"}],
    "ila": [{"p": "ایلام", "e": "Ilam"}, {"p": "دهلران", "e": "Dehloran"}, {"p": "ایوان", "e": "Eyvan"}, {"p": "آبدانان", "e": "Abdanan"}, {"p": "دره‌شهر", "e": "Darreh Shahr"}, {"p": "ارکواز", "e": "Arkavaz"}, {"p": "مهران", "e": "Mehran"}, {"p": "سرابله", "e": "Sarabeleh"}, {"p": "بدره", "e": "Badreh"}, {"p": "آسمان‌آباد", "e": "Asemanabad"}, {"p": "چوار", "e": "Chovar"}]
}

def update_json_files():
    base_path = r"c:\files\projects\Json-List-of-countries-states-and-cities-in-the-world\json\cites\ir"
    for code, cities in all_cities_data.items():
        file_path = os.path.join(base_path, f"{code}.json")

        # Load existing data if file exists
        if os.path.exists(file_path):
            with open(file_path, 'r', encoding='utf-8') as f:
                try:
                    data = json.load(f)
                except json.JSONDecodeError:
                    data = {}
        else:
            data = {}

        # Update data
        # Mapping rules: n: English, l: local (Persian)
        # Use existing keys or create new ones

        # First, create a map of existing Persian names to avoid duplicates
        existing_names = {item['l']: key for key, item in data.items()}

        for city in cities:
            p_name = city['p']
            e_name = city['e']

            if p_name in existing_names:
                # Update English name if it's different/missing?
                key = existing_names[p_name]
                data[key]['n'] = e_name
            else:
                # Add new city
                new_id = str(max([int(k) for k in data.keys()] + [0]) + 1)
                data[new_id] = {"n": e_name, "l": p_name}

        # Write back to file
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=1)
        print(f"Updated {file_path}")

if __name__ == "__main__":
    update_json_files()
